### ISSUE TITLE
Debt ceiling / isolated assets

### ISSUE THREAD

**Issue by sakulstra** [aave/aave-ui#133]
- [x] I have searched the [issues](https://github.com/aave/aave-ui/issues) of this repository and believe that this is not a duplicate.

## Summary 💡
https://governance.aave.com/t/introducing-aave-v3/6035

## Tasks 🔦

- [ ] UiPoolDataProvider needs to provide `DEBT_CEILING_DECIMALS` , isolationModeDebtCeiling, isolationModeTotalDebt
- [ ] the ui needs to check before borrow if debt ceiling allows borrowing `min(isolationModeDebtCeiling- isolationModeTotalDebt, availableLiquidity)`
